#!/bin/bash

read -p "Overwrite all configurations. Are you sure? (y/n): " -r
echo
if [[ ! $REPLY =~ ^[Yy]$ ]]
then
    [[ "$0" = "$BASH_SOURCE" ]] && exit 1 || return 1
fi

btop() {
  mkdir -p "$HOME/.config/btop"
  cp "$HOME/.de/btop/btop.conf" "$HOME/.config/btop/btop.conf"
  echo "btop"
}

cava() {
  mkdir -p "$HOME/.config/cava"
  cp "$HOME/.de/cava/config" "$HOME/.config/cava/config"
  echo "cava"
}

vscode() {
  mkdir -p "$HOME/.config/VSCodium/User"
  cp "$HOME/.de/code/keybindings.json" "$HOME/.config/VSCodium/User/keybindings.json"
  cp "$HOME/.de/code/settings.json" "$HOME/.config/VSCodium/User/settings.json"
  echo "vscode"
}

gtk() {
  mkdir -p "$HOME/.config/gtk-3.0"
  cp "$HOME/.de/gtk-3.0/gtk.css" "$HOME/.config/gtk-3.0/gtk.css"
  cp "$HOME/.de/gtk-3.0/gtk-dark.css" "$HOME/.config/gtk-3.0/gtk-dark.css"
  cp -r $HOME/.de/gtk-3.0/assets/* "$HOME/.config/gtk-3.0/assets/"
  echo "gtk"
}

lf() {
  mkdir -p "$HOME/.config/lf"
  cp "$HOME/.de/lf/colors" "$HOME/.config/lf/colors"
  cp "$HOME/.de/lf/icons" "$HOME/.config/lf/icons"
  cp "$HOME/.de/lf/lfrc" "$HOME/.config/lf/lfrc"
  cp "$HOME/.de/lf/previewer.sh" "$HOME/.config/lf/previewer.sh"
  cp "$HOME/.de/lf/run.sh" "$HOME/.config/lf/run.sh"
  echo "lf"
}

mpd() {
  mkdir -p "$HOME/.config/mpd/playlists"
  cp "$HOME/.de/mpd/mpd.conf" "$HOME/.config/mpd/mpd.conf"
  echo "mpd"
}

nvim() {
  # FIX: Outdated
  # mkdir -p "$HOME/.config/nvim/lua"
  # cp "$HOME/.de/nvim/init.lua" "$HOME/.config/nvim/init.lua"
  # cp -r $HOME/.de/nvim/lua/* "$HOME/.config/nvim/lua/"
  # echo "nvim"
}

xdefaults() {
  cp "$HOME/.de/.Xdefaults" "$HOME/.Xdefaults"
  echo "xdefaults"
}

desktop() {
  mkdir -p "$HOME/.config/hypr"
  mkdir -p "$HOME/.config/swaylock"
  mkdir -p "$HOME/.config/waybar"
  cp "$HOME/.de/hypr/hyprland.conf" "$HOME/.config/hypr/hyprland.conf"
  cp "$HOME/.de/swaylock/config" "$HOME/.config/swaylock/config"
  cp "$HOME/.de/waybar/config.jsonc" "$HOME/.config/waybar/config.jsonc"
  cp "$HOME/.de/waybar/style.css" "$HOME/.config/waybar/style.css"
}

btop
cava
gtk
vscode
lf
mpd
xdefaults
desktop
