#!/bin/bash

STACKED=$(hyprctl activewindow | grep grouped | cut -d " " -f2)
if [[ $STACKED != "0" && $STACKED != "" ]]; then
  printf ""
else
  printf ""
fi

# function handle {
#   if [[ ${1:0:12} == "activewindow" ]]; then
#     STACKED=$(hyprctl activewindow | grep grouped | cut -d " " -f2)
#     if [[ $STACKED != "0" && $STACKED != "" ]]; then
#       printf ""
#     else
#       printf ""
#     fi
#   fi
# }
#
# socat - "UNIX-CONNECT:/tmp/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock" | while read -r line; do handle "$line"; done
