#!/bin/bash

DMENU="bemenu -i"
COMMAND=$(echo -e "Brave\nFirefox\nGimp\nCode\nGodot\nFinder\nCava\nMedia Player\nActivity Monitor\nGPU Monitor\nMusic\nVideo\nPass\nSettings\nSystem" | $DMENU -p "Launch:");

case $COMMAND in
  "Brave") brave & ;;
  "Firefox") firefox & ;;
  "Gimp") gimp & ;;
  "Code") code & ;;
  "Godot") godot & ;;
  "Finder") foot -e ~/.config/lf/run.sh & ;;
  "Cava") foot -e cava & ;;
  "Activity Monitor") foot -e btop & ;;
  "GPU Monitor") foot -e nvtop & ;;
  "Settings") ~/.de/scripts/dmenu/settings & ;;
  "Music") ~/.de/scripts/dmenu/music & ;;
  "Video") ~/.de/scripts/dmenu/video & ;;
  "Pass") ~/.de/scripts/dmenu/pass & ;;
  "System") ~/.de/scripts/dmenu/system & ;;
esac
