#!/bin/bash

DMENU='bemenu -i'
COMMAND=$(echo -e "Close Session\nReboot\nShutdown" | $DMENU -p System:);

case $COMMAND in

  "Shutdown") shutdown now & ;;
  "Reboot") reboot & ;;
  "Close Session") hyprctl dispatch exit & ;;

esac
