#!/bin/bash

# Tokyo Night
black=#1a1b26
green=#9ece6a
white=#a9b1d6
grey=#24283b
blue=#88abf7
red=#f7768e
yellow=#e0af68
magenta=#9a7ecc

cpu() {
  cpu_val=$(grep -o "^[^ ]*" /proc/loadavg)

  printf "^c$black^^b$green^ 󰘚 "
  printf "^c$white^^b$grey^ $cpu_val%% "
}

mem() {
  printf "^c$black^^b$green^ 󰍛 "
  printf "^c$white^^b$grey^ $(free -h | awk '/^Mem/ { print $3 }' | sed s/i//g) "
}

disk() {
  printf "^c$black^^b$green^ 󰋊 "
  printf "^c$white^^b$grey^ %s " $(df -h -l | awk '/\/$/ { print $5 }')
}

temp() {
  temp_val=$(cat /sys/devices/virtual/thermal/thermal_zone0/hwmon1/temp1_input)
  div_val=1000

  printf "^c$black^^b$red^ 󰔏 "
  printf "^c$white^^b$grey^ %s°C " $((temp_val / div_val))
}

volume() {
  printf "^c$black^^b$blue^ 󰕾 "
	case "$(pactl get-sink-mute @DEFAULT_SINK@ | awk '/Mute:.*/ { print $2 }')" in
	no) printf "^c$white^^b$grey^ %s " $(pactl get-sink-volume @DEFAULT_SINK@ | awk '/[0-9]%/ { print $5 }') ;;
	yes) printf "^c$white^^b$grey^ Muted " ;;
	esac
}

brightness() {
  printf "^c$black^^b$yellow^ 󰖙 "
  printf "^c$white^^b$grey^ %.0f " $(cat /sys/class/backlight/*/brightness)
}

battery() {
  get_capacity="$(cat /sys/class/power_supply/BAT0/capacity)"
  printf "^c$black^^b$red^ 󰂀 "
  printf "^c$white^^b$grey^ $get_capacity%% "
}

clock() {
	printf "^c$black^^b$blue^ 󰃭 "
	printf "^c$white^^b$grey^ $(date '+%a %d/%m %H:%M') "
}

wlan() {
	case "$(cat /sys/class/net/wlan0/operstate 2>/dev/null)" in
  up) printf "^c$black^^b$blue^ 󰖩 ^c$white^^b$grey^ Connected " ;;
	down) printf "^c$black^^b$blue^ 󰖪 ^c$white^^b$grey^ Connected " ;;
	esac
}

com() {
  FILE="/tmp/dmenu_com"
  if [ -f $FILE ]; then
    printf "^c$black^^b$green^ 󰂚 "
    printf "^c$white^^b$grey^ %s " "$(cat /tmp/dmenu_com)"
  fi
}

mpd() {
  STATUS=$(mpc status 2>&1)
  if [[ $STATUS = *"Connection refused"* ]]; then
    printf "^c$black^^b$blue^ 󰝚 ^c$white^^b$grey^ Disconnected "
    return
  fi

  if [[ "$(mpc status %random%)" = "on" ]]; then
    printf "^c$black^^b$green^ 󰒝 ^c$white^^b$grey^ Random ^b$black^ "
  fi

  if [[ "$(mpc status %single%)" = "on" ]]; then
    printf "^c$black^^b$yellow^ 󰕇 ^c$white^^b$grey^ Repeat ^b$black^ "
  fi

  SONG=$(mpc current)
  if [[ $SONG ]]; then
    printf "^c$black^^b$blue^ 󱫝 ^c$white^^b$grey^ %s/%s ^b$black^ " "$(mpc status %currenttime%)" "$(mpc status %totaltime%)"
    case "$(mpc status %state%)" in
      playing) printf "^c$black^^b$blue^ 󱖑 ^c$white^^b$grey^ %s " "${SONG%.*}";;
      paused) printf "^c$black^^b$blue^ 󱖒 ^c$white^^b$grey^ %s " "${SONG%.*}";;
    esac
  else
    printf "^c$black^^b$blue^ 󰝚 ^c$white^^b$grey^ Connected "
  fi
}

while true; do
  sleep 1 && xsetroot -name "$(com)^b$black^ $(cpu)^b$black^ $(mem)^b$black^ $(disk)^b$black^ $(brightness)^b$black^ $(battery)^b$black^ $(temp)^b$black^ $(volume)^b$black^ $(wlan)^b$black^ $(clock);$(mpd)"
done
