#!/bin/bash

external_monitor=$(xrandr -q | grep 'HDMI-1-0')
if [[ $external_monitor = *disconnected* ]]; then
  sed -i 's/dpi:.*/dpi: 96/g' ~/.Xresources

	xrandr --output HDMI-1-0 --off
else
  # sed -i 's/dpi:.*/dpi: 192/g' ~/.Xresources

  # --set "PRIME Synchronization 1" 
	# xrandr --fbmm 7680x2160 --output eDP --primary --scale 2x2 --mode 1920x1080 --output HDMI-1-0 --pos 3840x0 --mode 3840x2160 --rate 60 --scale 1x1
	xrandr --output eDP --off --output HDMI-1-0 --mode 3840x2160 --rate 60
fi
