#!/bin/bash

COMMAND=$(echo -e "Browser\nMedia Browser\nGimp\nFinder\nCava\nActivity Monitor\nGPU Monitor\nGodot\nCode\nMusic\nVideo\nPass\nSettings\nSystem" | $DMENU -p "Launch:");

case $COMMAND in
  "Browser") librewolf & ;;
  "Media Browser") firefox & ;;
  "Gimp") gimp & ;;
  "Finder") foot -e lf & ;;
  "Cava") foot -e cava & ;;
  "Activity Monitor") foot -e btop & ;;
  "GPU Monitor") foot -e nvtop & ;;
  "Godot") godot --rendering-driver opengl3 & ;;
	"Code") desktop-menu-code & ;;
  "Music") desktop-menu-music & ;;
  "Video") desktop-menu-video & ;;
  "Pass") desktop-menu-pass & ;;
  "Settings") desktop-menu-settings & ;;
  "System") desktop-menu-system & ;;
esac
